apiVersion: tutorials.piunnerup.com/v1
kind: Cake
metadata:
  name: cake-sample
spec:
  port: 8099
  replicaCount: 1
  DECORATION: "hat"
  COLOUR: "colour"
  MESSAGE: "They are edible"
  BACKGROUND: "Aquamarine"
